version: "3.9"
services:

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./.docker/back/conf/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network
    links:
      - backend

  backend:
    build:
      context: ./
      dockerfile: .docker/back/Dockerfile
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    links:
      - pgsql

  pgsql:
    image: postgres:13.2-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=test-assignment
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-user
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: .docker/front/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
